# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f74fb8a411a2f62d04465a3eecc30d27ce9a84564b7a8795790f33e46c39fb3de47ce4482c4f4e8aa6e18c24fbd70053112419664365ad643935d7dd967ef3f

test:
  secret_key_base: 3fec5f3849f5c479085e678dcab2c723783ed9bb3ed3e57068c2a282a7056b0d6125dafd87a4f2f698a16ba3fa5f5e0a84f2d8d4d1395848cad23345a56caefc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
